CREATE DATABASE SubwayManagement
GO
USE SubwayManagement
GO


CREATE TABLE TRAIN_TYPES(
    TRAIN_TYPE_ID BIGINT NOT NULL,
    TRAIN_TYPE VARCHAR(255) NOT NULL,
    CONSTRAINT train_types_train_type_id_primary PRIMARY KEY(TRAIN_TYPE_ID)
)


CREATE TABLE TRAIN_DETAILS(
    TRAIN_ID BIGINT NOT NULL,
    TRAIN_NAME VARCHAR(255) NOT NULL,
    COACHES_NUM BIGINT NOT NULL,
    TRAIN_TYPE_ID BIGINT NOT NULL,
	CONSTRAINT train_details_train_id_primary PRIMARY KEY(TRAIN_ID),
	CONSTRAINT train_details_train_type_id_foreign FOREIGN KEY(TRAIN_TYPE_ID) REFERENCES TRAIN_TYPES(TRAIN_TYPE_ID)
)


CREATE TABLE PROVINCE_COUNTRY(
    PROVINCE VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    CONSTRAINT province_country_province_primary PRIMARY KEY(PROVINCE)
)


CREATE TABLE STATIONS(
    STATION_ID BIGINT NOT NULL,
    STATION_STREET VARCHAR(255) NOT NULL,
    STATION_CITY VARCHAR(255) NOT NULL,
    PROVINCE VARCHAR(255) NOT NULL,
    POSTAL_CODE VARCHAR(255) NOT NULL,
    STATION_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT stations_station_id_primary PRIMARY KEY(STATION_ID),
    CONSTRAINT stations_province_foreign FOREIGN KEY(PROVINCE) REFERENCES PROVINCE_COUNTRY(PROVINCE)
)


CREATE TABLE ROUTES(
    ROUTE_ID BIGINT NOT NULL,
    STATION_ID BIGINT NOT NULL,
    TRAIN_ID BIGINT NOT NULL,
    DEPARTURE_TIME TIME NOT NULL,
    ARRIVAL_TIME TIME NOT NULL,
    ROUTE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT routes_route_id_primary PRIMARY KEY(ROUTE_ID),
    CONSTRAINT routes_train_id_foreign FOREIGN KEY(TRAIN_ID) REFERENCES TRAIN_DETAILS(TRAIN_ID),
    CONSTRAINT routes_station_id_foreign FOREIGN KEY(STATION_ID) REFERENCES STATIONS(STATION_ID)
)


CREATE TABLE PASSENGERS(
    PASN_ID BIGINT NOT NULL,
    PASN_FNAME VARCHAR(255) NOT NULL,
    PASN_LNAME VARCHAR(255) NOT NULL,
    PASN_AGE BIGINT NOT NULL,
    PASN_PHONE_NUM BIGINT NOT NULL,
    PASN_EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT passengers_pasn_id_primary PRIMARY KEY(PASN_ID)
)


CREATE TABLE PASSES(
    PASS_ID BIGINT NOT NULL,
    TRAIN_ID BIGINT NOT NULL,
    PASS_ISSUED_DATE DATE NOT NULL,
    PASS_EXPIRE_DATE DATE NOT NULL,
    PRICE DECIMAL(8, 2) NOT NULL,
    PASN_ID BIGINT NOT NULL,
    ROUTE_ID BIGINT NOT NULL,
    CONSTRAINT pass_pass_id_primary PRIMARY KEY(PASS_ID),
    CONSTRAINT pass_route_id_foreign FOREIGN KEY(ROUTE_ID) REFERENCES ROUTES(ROUTE_ID),
    CONSTRAINT pass_train_id_foreign FOREIGN KEY(TRAIN_ID) REFERENCES TRAIN_DETAILS(TRAIN_ID),
    CONSTRAINT pass_pasn_id_foreign FOREIGN KEY(PASN_ID) REFERENCES PASSENGERS(PASN_ID)
)


CREATE TABLE ROUTES_STATIONS(
    ROUTE_ID BIGINT NOT NULL,
    STATION_ID BIGINT NOT NULL,
	CONSTRAINT routes_stations_station_id_foreign FOREIGN KEY(STATION_ID) REFERENCES STATIONS(STATION_ID),
	CONSTRAINT routes_stations_route_id_foreign FOREIGN KEY(ROUTE_ID) REFERENCES ROUTES(ROUTE_ID)
)
