CREATE DATABASE StudentEnrollmentSystem
GO
USE StudentEnrollmentSystem
GO


CREATE TABLE STUDENTS(
    STU_ID BIGINT NOT NULL,
    STU_FNAME VARCHAR(255) NOT NULL,
    STU_LNAME VARCHAR(255) NOT NULL,
    STU_AGE BIGINT NOT NULL,
    STU_DOB DATE NOT NULL,
    STU_EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT students_stu_id_primary PRIMARY KEY(STU_ID)
)


CREATE TABLE INSTRUCTORS(
    INS_ID BIGINT NOT NULL,
    INS_FNAME VARCHAR(255) NOT NULL,
    INS_LNAME VARCHAR(255) NOT NULL,
    INS_AGE BIGINT NOT NULL,
    INS_DOB DATE NOT NULL,
    INS_EMAIL VARCHAR(255) NOT NULL,
	CONSTRAINT instructors_ins_id_primary PRIMARY KEY(INS_ID)
)


CREATE TABLE ASSESSMENTS(
    ASM_ID BIGINT NOT NULL,
    ASM_TYPE VARCHAR(255) NOT NULL,
    CONSTRAINT assessments_asm_id_primary PRIMARY KEY(ASM_ID)
)


CREATE TABLE GRADES(
    GRADE_ID BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    ASM_ID BIGINT NOT NULL,
    STU_ID BIGINT NOT NULL,
    CONSTRAINT grades_grade_id_primary PRIMARY KEY(GRADE_ID),
    CONSTRAINT grades_stu_id_foreign FOREIGN KEY(STU_ID) REFERENCES STUDENTS(STU_ID),
    CONSTRAINT grades_course_id_foreign FOREIGN KEY(COURSE_ID) REFERENCES COURSES(COURSE_ID),
    CONSTRAINT grades_asm_id_foreign FOREIGN KEY(ASM_ID) REFERENCES ASSESSMENTS(ASM_ID)
)


CREATE TABLE DAD(
    DAD_ID BIGINT NOT NULL,
    DAD_FNAME VARCHAR(255) NOT NULL,
    DAD_LNAME VARCHAR(255) NOT NULL,
    DAD_AGE BIGINT NOT NULL,
    DAD_DOB DATE NOT NULL,
    DAD_EMAIL VARCHAR(255) NOT NULL,
	CONSTRAINT dad_dad_id_primary PRIMARY KEY(DAD_ID)
)

CREATE TABLE MOM(
    MOM_ID BIGINT NOT NULL,
    MOM_FNAME VARCHAR(255) NOT NULL,
    MOM_LNAME VARCHAR(255) NOT NULL,
    MOM_AGE BIGINT NOT NULL,
    MOM_DOB DATE NOT NULL,
    MOM_EMAIL VARCHAR(255) NOT NULL,
	CONSTRAINT mom_mom_id_primary PRIMARY KEY(MOM_ID)
)


CREATE TABLE PARENTS(
    PARENT_ID BIGINT NOT NULL,
    MOM_ID BIGINT NOT NULL,
    DAD_ID BIGINT NOT NULL,
	CONSTRAINT parents_parent_id_primary PRIMARY KEY(PARENT_ID),
	CONSTRAINT parents_mom_id_foreign FOREIGN KEY(MOM_ID) REFERENCES MOM(MOM_ID),
	CONSTRAINT parents_dad_id_foreign FOREIGN KEY(DAD_ID) REFERENCES DAD(DAD_ID)
)


CREATE TABLE REGISTER(
    STU_ID BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
	CONSTRAINT register_stu_id_foreign FOREIGN KEY(STU_ID) REFERENCES STUDENTS(STU_ID),
	CONSTRAINT register_course_id_foreign FOREIGN KEY(COURSE_ID) REFERENCES COURSES(COURSE_ID)
)


CREATE TABLE COURSES(
    COURSE_ID BIGINT NOT NULL,
    COURSE_TITLE VARCHAR(255) NOT NULL,
    COURSE_CDN BIGINT NOT NULL,
    COURSE_START_DATE DATE NOT NULL,
    COURSE_END_DATE DATE NOT NULL,
    INS_ID BIGINT NOT NULL,
    CONSTRAINT courses_course_id_primary PRIMARY KEY(COURSE_ID),
    CONSTRAINT courses_ins_id_foreign FOREIGN KEY(INS_ID) REFERENCES INSTRUCTORS(INS_ID)
)


CREATE TABLE STUDENTS_PARENTS(
    STU_ID BIGINT NOT NULL,
    PARENT_ID BIGINT NOT NULL,
	CONSTRAINT students_parents_stu_id_foreign FOREIGN KEY(STU_ID) REFERENCES STUDENTS(STU_ID),
	CONSTRAINT students_parents_parent_id_foreign FOREIGN KEY(PARENT_ID) REFERENCES PARENTS(PARENT_ID)
)
