-- Create a stored procedure to retrieve the monthly appointment schedule for a specific doctor.
CREATE OR ALTER PROCEDURE sp_GetMonthlyAppointmentSchedule
	@Doc_Id BIGINT,
	@Month INT, 
	@Year INT
AS 
BEGIN
	SELECT CONCAT(d.DOC_FNAME, ' ', d.DOC_LNAME) AS DOC_FULLNAME, CONCAT(p.PAT_FNAME, ' ', p.PAT_LNAME) AS PAT_FULLNAME,  a.APP_DATE, CONCAT(a.APP_START_TIME, ' ', a.APP_END_TIME) AS APP_TIME
	FROM DOCTORS d
	INNER JOIN APPOINTMENTS a ON d.APP_ID = a.APP_ID
	INNER JOIN PATIENTS_APPOINTMENTS pa ON a.APP_ID = pa.APP_ID
	INNER JOIN PATIENTS p ON pa.PAT_ID = p.PAT_ID
	WHERE d.DOC_ID = @Doc_Id AND MONTH(a.APP_DATE) = @Month AND YEAR(a.APP_DATE) = @Year
	ORDER BY a.APP_DATE, a.APP_START_TIME
END

GO