-- Create the Hospital Management System Database
CREATE DATABASE HospitalManagement
GO
USE HospitalManagement
GO

-- Create Provinces Table
CREATE TABLE PROVINCES (
    PROVINCE_ID BIGINT NOT NULL PRIMARY KEY,
    PROVINCE VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL
)

-- Create Hospitals Table
CREATE TABLE HOSPITALS(
    HOS_ID BIGINT NOT NULL PRIMARY KEY,
    HOS_NAME VARCHAR(255) NOT NULL,
    HOS_STREET VARCHAR(255) NOT NULL,
    HOS_CITY VARCHAR(255) NOT NULL,
    PROVINCE_ID BIGINT NOT NULL,
    HOS_COUNTRY VARCHAR(255) NOT NULL,
    FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCES(PROVINCE_ID)
)

-- Create Professions Table
CREATE TABLE PROFESSIONS(
    PROFF_ID BIGINT NOT NULL PRIMARY KEY,
    PROFF_TYPE VARCHAR(255) NOT NULL,
)

-- Create Departments Table
CREATE TABLE DEPARTMENTS(
    DEPT_ID BIGINT NOT NULL PRIMARY KEY,
    DEPT_NAME VARCHAR(255) NOT NULL,
    HOS_ID BIGINT NOT NULL,
    FOREIGN KEY (HOS_ID) REFERENCES HOSPITALS(HOS_ID)
)

-- Create Doctors Table
CREATE TABLE DOCTORS(
    DOC_ID BIGINT NOT NULL PRIMARY KEY,
    HOS_ID BIGINT NOT NULL,
    DEPT_ID BIGINT NOT NULL,
    DOC_FNAME VARCHAR(255) NOT NULL,
    DOC_LNAME VARCHAR(255) NOT NULL,
    DOC_CONTACT VARCHAR(255) NOT NULL,
    DOC_DOB DATE NOT NULL,
    DOC_EMAIL VARCHAR(255) NOT NULL,
    PROFF_ID BIGINT NOT NULL,
    FOREIGN KEY (HOS_ID) REFERENCES HOSPITALS(HOS_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID),
    FOREIGN KEY (PROFF_ID) REFERENCES PROFESSIONS(PROFF_ID)
)

-- Create Nurses Table
CREATE TABLE NURSES(
    NUR_ID BIGINT NOT NULL PRIMARY KEY,
    HOS_ID BIGINT NOT NULL,
    DEPT_ID BIGINT NOT NULL,
    NUR_FNAME VARCHAR(255) NOT NULL,
    NUR_LNAME VARCHAR(255) NOT NULL,
    NUR_DOB DATE NOT NULL,
    NUR_CONTACT VARCHAR(255) NOT NULL,
    NUR_EMAIL VARCHAR(255) NOT NULL,
    FOREIGN KEY (HOS_ID) REFERENCES HOSPITALS(HOS_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
)

-- Create Rooms Table
CREATE TABLE ROOMS(
    ROOM_ID BIGINT NOT NULL PRIMARY KEY,
    ROOM_CAPACITY BIGINT NOT NULL,
    ROOM_AVAILABILITY BIGINT NOT NULL,
    ROOM_TYPE VARCHAR(255) NOT NULL,
)

-- Create Patients Table
CREATE TABLE PATIENTS(
    PAT_ID BIGINT NOT NULL PRIMARY KEY,
    ROOM_ID BIGINT NOT NULL,
    PAT_FNAME VARCHAR(255) NOT NULL,
    PAT_LNAME VARCHAR(255) NOT NULL,
    PAT_GENDER VARCHAR(255) NOT NULL,
    PAT_DOB DATE NOT NULL,
    PAT_CONTACT VARCHAR(255) NOT NULL,
    PAT_EMAIL VARCHAR(255) NOT NULL,
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
)

-- Create Appointments Table
CREATE TABLE APPOINTMENTS(
    APP_ID BIGINT NOT NULL PRIMARY KEY,
    APP_DATE DATE NOT NULL,
    APP_START_TIME TIME NOT NULL,
    APP_END_TIME TIME NOT NULL,
    APP_DETAILS VARCHAR(255) NOT NULL,
    DOC_ID BIGINT NOT NULL,
    FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID)
)

-- Create Patients_Appointments Table
CREATE TABLE PATIENTS_APPOINTMENTS(
    PAT_ID BIGINT NOT NULL ,
    APP_ID BIGINT NOT NULL,
    FOREIGN KEY (PAT_ID) REFERENCES PATIENTS(PAT_ID),
    FOREIGN KEY (APP_ID) REFERENCES APPOINTMENTS(APP_ID)
)

-- Create Bills Table
CREATE TABLE BILLS(
    BILL_ID BIGINT NOT NULL PRIMARY KEY,
    PAT_ID BIGINT NOT NULL,
    BILL_AMOUNT BIGINT NOT NULL,
    FOREIGN KEY (PAT_ID) REFERENCES PATIENTS(PAT_ID)
)

-- Create Records Table
CREATE TABLE RECORDS(
    RECORD_ID BIGINT NOT NULL PRIMARY KEY,
    APP_ID BIGINT NOT NULL,
    FOREIGN KEY (APP_ID) REFERENCES APPOINTMENTS(APP_ID)
)

-- Create Receptionists Table
CREATE TABLE RECEPTIONISTS(
    RECEP_ID BIGINT NOT NULL PRIMARY KEY,
    HOS_ID BIGINT NOT NULL,
    RECEP_FNAME VARCHAR(255) NOT NULL,
    RECEP_LNAME VARCHAR(255) NOT NULL,
    RECEP_CONTACT VARCHAR(255) NOT NULL,
    RECEP_EMAIL VARCHAR(255) NOT NULL,
    RECEP_DOB DATE NOT NULL,
    FOREIGN KEY (HOS_ID) REFERENCES HOSPITALS(HOS_ID)
)

-- Create Receptionists_Records Table
CREATE TABLE RECEPTIONISTS_RECORDS(
    RECORD_ID BIGINT NOT NULL,
    RECEP_ID BIGINT NOT NULL,
    FOREIGN KEY (RECEP_ID) REFERENCES RECEPTIONISTS(RECEP_ID),
    FOREIGN KEY (RECORD_ID) REFERENCES RECORDS(RECORD_ID)
)

-- Create Doctors_Patients Table
CREATE TABLE DOCTORS_PATIENTS(
    DOC_ID BIGINT NOT NULL,
    PAT_ID BIGINT NOT NULL,
    FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID),
    FOREIGN KEY (PAT_ID) REFERENCES PATIENTS(PAT_ID)
)

-- Create Teams Table
CREATE TABLE TEAMS(
    TEAM_ID BIGINT NOT NULL PRIMARY KEY,
    DOC_ID BIGINT NOT NULL,
    NUR_ID BIGINT NOT NULL,
    FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID),
    FOREIGN KEY (NUR_ID) REFERENCES NURSES(NUR_ID)
)

-- Create Medications Table
CREATE TABLE MEDICATIONS(
    MED_ID BIGINT NOT NULL PRIMARY KEY,
    MED_NAME VARCHAR(255) NOT NULL,
    MED_DESCRIPTION TEXT NOT NULL,
)

-- Create Procedures Table
CREATE TABLE PROCEDURES(
    PROC_ID BIGINT NOT NULL PRIMARY KEY,
    PROC_NAME VARCHAR(255) NOT NULL,
    PROC_DESCRIPTION TEXT NOT NULL,
)

-- Create Patient_Medications Table
CREATE TABLE PATIENT_MEDICATIONS(
    PAT_ID BIGINT NOT NULL,
    MED_ID BIGINT NOT NULL,
    PRESCRIPTION_DATE DATE NOT NULL,
    FOREIGN KEY (PAT_ID) REFERENCES PATIENTS(PAT_ID),
    FOREIGN KEY (MED_ID) REFERENCES MEDICATIONS(MED_ID)
)

-- Create Patient_Procedures Table
CREATE TABLE PATIENT_PROCEDURES(
    PAT_ID BIGINT NOT NULL,
    PROC_ID BIGINT NOT NULL,
    PROCEDURE_DATE DATE NOT NULL,
    FOREIGN KEY (PAT_ID) REFERENCES PATIENTS(PAT_ID),
    FOREIGN KEY (PROC_ID) REFERENCES PROCEDURES(PROC_ID)
)
